---

ps.expected:
  sshd:
    cmd: "sshd -D"
    user: "root"
    tags:
      - system
      - sshd
  ntpd:
    cmd: "ntpd"
    user: "ntp"
    tags:
      - system
      - ntpd
  elasticsearch:
    cmd: "java.*org\\.elasticsearch\\.bootstrap\\.Elasticsearch start"
    user: "elastic"
    tags:
      - elasticsearch
  logstash:
    cmd: "java.*logstash.*org\\.jruby\\.Main"
    user: "root"
    tags:
      - logstash
  kibana:
    cmd: "node.*kibana"
    user: "www-data"
    tags:
      - kibana
  nginx:
    cmd: "nginx.*master"
    user: "root"
    tags:
      - nginx
  influxdb:
    cmd: "influxd"
    user: "influxdb"
    tags:
      - influxdb
  riemann-server:
    cmd: "java.*riemann\\.jar.*start"
    user: "riemann"
    tags:
      - riemann
      - riemann-server
  riemann-dash:
    cmd: "ruby.*riemann-dash"
    user: "www-data"
    tags:
      - riemann
      - riemann-dash

checksum.files:
  - path: /etc/passwd
    tags:
      - system
  - path: /etc/group
    tags:
      - system
